syscat/itasset/urls.py
from django.urls import path

from . import views

app_name = 'itasset'


urlpatterns = [
    # Главная страница.
    path('', views.index, name='main'),
    # Подробно актив
    path('itasset/<int:itasset_id>/',
         views.asset_detail,
         name='itasset_detail'),
    # Создание актива
    path('create/',
         views.asset_create,
         name='itasset_create'),
    # Редактирование актива
    path(
         'itasset/<int:asset_id>/edit/',
         views.asset_edit,
         name='itasset_edit'
     ),
    # Страница со списком активов.
    path('itasset/', views.itasset_list, name='itasset_list'),
]

syscat/syscat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('', include('itasset.urls', namespace='itasset')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

syscat/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path('signup/', SignUp.as_view(), name='signup'),
]

syscat/templates/includes/assetcard.html
{% load thumbnail %}
{% load static %}
<div class="row gy-4 gy-md-0" style = "background-color: #28364112; border-radius: 26px;  padding: 10px auto; margin: 20px auto 20px auto ">
    <div class="col-md-5">
        <div class="p-xl-5 m-xl-5">
            {% thumbnail asset.image "400x400" crop="center" upscale=False as im %}
            <img class="rounded img-fluid w-100 fit-cover" src="{{ im.url }}"/>
            {% endthumbnail %}
        </div>
    </div>
    <div class="col-md-7 d-md-flex align-items-md-center">
        <div style="max-width: 750px;">
            <h2 class="text-uppercase fw-bold">{{ asset.title }}</h2>
            <pre>{{ asset.description }}</pre>
            <p class="post-meta"
               style="color:#6c757d;
                      font-size: 18px;
                      font-style: italic;">
                Последние изменения: {{ asset.author }} &nbsp;
                {{ asset.created }}
            </p>
            {% if user.is_authenticated %}
                {% if asset.author == user %}
                    <a class="btn btn-outline-primary" style = "border-radius: 13px;" role="button" href="{% url 'itasset:itasset_edit' asset.id %}" >
                        <img src="{% static 'img/edit.svg' %}"  style= "width:30px; height:30px;" title="Редактировать" >
                    </a>
                {% endif %}
            {% endif %}
            <a class="btn btn-outline-primary" style = "border-radius: 13px;"
               role="button"
               href="{% url 'itasset:itasset_detail' asset.id %}">
                <img src="{% static 'img/open.svg' %}"  style= "width:30px; height:30px;" title="Подробно" >
            </a>
        </div>
        <br>
    </div>
</div>

syscat/templates/includes/check_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">{{ field.label }}: {{ error|escape }}</div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">{{ field.label }}: {{ error|escape }}</div>
  {% endfor %}
{% endif %}

syscat/templates/includes/fields.html
{% load user_filters %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link rel="stylesheet" href="{% static 'css/accordion.css' %}"/>

{% for field in form %}

{% if field.field.required %}
  <div class="container" style = "margin: 10px auto; padding-right:0px; padding-left: 0px;">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      <span class="required text-danger">*</span>
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% else %}
<button class="it_accordion" type="button"> {{ field.label }} </button>
<div class="it_acc_panel">
<div class="container" style = "margin: 10px auto; padding-right:0px; padding-left: 0px;">
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}
      </small>
    {% endif %}
    {% if field.name == "files" %}
      {% include 'includes/file_cards.html' %}
    {% endif %}

</div>    
</div>
{% endif %}
{% endfor %}
<script type="text/javascript">
var acc = document.getElementsByClassName("it_accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
      panel.children[0].focus();
    } 
   
  });
}
</script>

syscat/templates/includes/file_cards.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/file_card.css' %}"/>
<div class="card-group d-sm-inline-flex">
{% for file in files %}
<a href="{{ file.asset_file.url }}">
<div class="file_card">
  <img class="file_card-image" src="{% static 'img/file.svg' %}" alt="Card image cap">
  <div class="file_card-content"> 
    <p class="file_card-text">{{ file.filename }}</p>
  </div>
</div>
</a>
{% endfor %}
</div>

syscat/templates/includes/footer.html
{% load static %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto">
        <ul class="list-inline text-center" style = "font-size: 16px;">
          <li>
            <img src="{% static 'img/sycat.png' %}" style = "width: 40px; height: 40px;">
          </li>
          <li>
            <br>
            <p>© {{ year }} Copyright Khizhnyak R.</p>    
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

syscat/templates/includes/modal_login.html
{% load static %}
<div id="id01" class="modal">
  <form class="modal-content animate"
        action="{% url 'users:login' %}"
        method="post">
    {% csrf_token %}
    <div class="screen__background">
      <span class="screen__background__shape screen__background__shape4"></span>
      <span class="screen__background__shape screen__background__shape3"></span>
      <span class="screen__background__shape screen__background__shape2"></span>
      <span class="screen__background__shape screen__background__shape1"></span>
    </div>
    <div class="screen__content">
      <div class="imgcontainer">
        <span onclick="document.getElementById('id01').style.display='none'"
              class="close"
              title="Закрыть">&times;</span>
        <img src="{% static 'img/account.svg' %}"  alt="Avatar" class="avatar">
      </div>
      <div class="container" style = "margin: 54px auto;">
        <label for="username" style = "font-weight: 100;">
          <b>Имя пользователя</b>
        </label>
        <input type="text" placeholder="Имя пользователя" name="username" required>
        <label for="password" style = "font-weight: 100;">
          <b>Пароль</b>
        </label>
        <input type="password" placeholder="Пароль" name="password" required>
        <button class="button modal_login__submit" type="submit">
          <span class="button__text">ВОЙТИ</span>
          <i class="button__icon fa fa-chevron-right" style="font-size:16px"></i>
        </button>
        <br/>
        <style>
                div {width: 100%;}
                a {display: block; text-align: center; font-size: 10pt; color:#1C272D;}
        </style>
        <a class="forgot" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
      </div>
    </div>
  </form>
</div>
<script>
    // Get the modal
    var modal = document.getElementById('id01');
    
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

syscat/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <div class="pagination-wrapper">
    <div class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <a class="prev page-numbers"
           href="?page={{ page_obj.previous_page_number }}"
           aria-label="Previous"><span aria-hidden="true">«</span> </a>
      {% else %}
        <a class="prev page-numbers disabled" aria-label="Previous"><span aria-hidden="true">«</span> </a>
      {% endif %}
      {% for i in pages_count %}
        {% if page_obj.number == i  %}
          <span aria-current="page" class="page-numbers current">{{ i }}</span>
        {% else %}
          <a class="page-numbers" href="?page={{ i }}">{{ i }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="next page-numbers"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next"><span aria-hidden="true">»</span></a>
      {% else %}
        <a class="next page-numbers disabled" aria-label="Next"><span aria-hidden="true">»</span></a>
      {% endif %}
    </div>
  </div>
{% endif %}