syscat/itasset/urls.py
from django.urls import path

from . import views

app_name = 'itasset'


urlpatterns = [
    # Главная страница.
    path('', views.index, name='main'),
    # Подробно актив
    path('itasset/<int:itasset_id>/',
         views.asset_detail,
         name='itasset_detail'),
    # Создание актива
    path('create/',
         views.asset_create,
         name='itasset_create'),
    # Редактирование актива
    path(
         'itasset/<int:asset_id>/edit/',
         views.asset_edit,
         name='itasset_edit'
     ),
    # Страница со списком активов.
    path('itasset/', views.itasset_list, name='itasset_list'),
]

syscat/syscat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('', include('itasset.urls', namespace='itasset')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

syscat/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path('signup/', SignUp.as_view(), name='signup'),
]

syscat/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        {% load static %}
        <meta charset="utf-8"/>
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>
        <meta name="description" content="SyCat IT Systems catalogue"/>
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/mycss.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/paginator.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/cards-list.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/float_m.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/modal_login.css' %}"/>
        <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}"/>
        <link rel="icon" href="{% static 'img/fav/favicon.ico' %}"  type="image">
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'img/fav/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'img/fav/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'img/fav/favicon-16x16.png' %}">
        <title>
            {% block title %}
                SyCat каталог
            {% endblock title %}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'itasset:main' %}" style = "color: #1c272d; font-weight: 800; font-size: 28px;">
                    <img src="{% static 'img/sycat.png' %}" style = "width: 50px; height: 50px;">
                    SyCat
                </a>
                <button data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        class="navbar-toggler"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'itasset:main' %}">ДОМОЙ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'itasset:itasset_list' %}">АКТИВЫ</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'itasset:itasset_create' %}">ДОБАВИТЬ АКТИВ</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle nav-link" aria-expanded = "false" data-bs-toggle="dropdown" href="#">
                                    {{ user.username }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-item">
                                        <a class="nav-link" href="{% url 'users:logout' %}">ВЫЙТИ</a>
                                    </li>
                                    <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'users:password_change' %}">СМЕНИТЬ ПАРОЛЬ</a>
                                    </li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link"  onclick="document.getElementById('id01').style.display='block'" >войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:signup' %}">регистрация</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <header class="masthead"
                style="background-image:url('{% static 'img/bg.png' %}'); height: 450px;">
            <div class="overlay"></div>
                    
                        <div class="site-heading mx-auto position-relative">
                            {% block page_header %}
                                <h1>SyCat каталог</h1>
                                <span class="subheading">Паспортизация ИТ активов компании</span>
                            {% endblock page_header %}
                        </div>
                    
        </header>
        <main>
            <div class="row">
                {% block overall_content %}
                {% endblock overall_content %}
                <div class="col-md-3 col-xxl-3">
                    {% block floating_menu %}
                    {% endblock floating_menu %}
                </div>
                <div class="col-md-7 col-xxl-9" style="background-color: #28364112; border-radius: 26px;">
                        {% block top_pagination %}
                        {% endblock top_pagination %}
                        {% block content %}
                        {% endblock content %}
                        {% block bot_pagination %}
                        {% endblock bot_pagination %}
                </div>
                
                
            </div>
        {% include 'includes/footer.html' %}
        {% include 'includes/modal_login.html' %}
        </main>
    <script src="{% static 'js/script.min.js' %}"></script>
    </body>
    
</html>